wenxuecity:
    uri: http://www.wenxuecity.com/
    depth: 1
    home-page-content:
        - tag: div
          class: content
    article-page-content:
        - tag: div
          class: article
          id: articleContent
        - tag: div
          id: msgbodyContent
    article-timestamp:
        - tag: time
        - tag: span
          class: date
    title-trim: www.wenxuecity.com|- 文学城
    filter-patterns:
        - ^/.*/\d+.html
        - ^http://.*.wenxuecity.com/.*/\d+.html
