wenxuecity:
    # general paramters
    name: wenxuecity
    alias: 文学城
    root: http://www.wenxuecity.com/
    depth: 1
    summary-len: 100

    # parameters to parse home page to get article links 
    home-page-content:
        - tag: div
          class: content
    article-links-filter-patterns:
        - ^/.*/\d+.html
        - ^http://.*.wenxuecity.com/.*/\d+.html

    # parameters to parse article content
    article-content-container:
        - tag: div
          class: mainwrapper
        - tag: div
          id: content
    article-content-title:
        tag: h3
    article-content:
        - tag: div
          class: article
          id: articleContent
        - tag: div
          id: msgbodyContent
    article-timestamp:
        - tag: time
        - tag: span
          class: date
    article-comments:
        user-date:
            tag: div
            class: reply
        comment:
            tag: div
            class: summary
    title-trim: www.wenxuecity.com|- 文学城

zhihudaily:
    # general paramters
    name: zhihudaily
    alias: 知乎日报
    root: http://daily.zhihu.com/
    depth: 1
    summary-len: 100

    # parameters to parse home page to get article links 
    home-page-content:
        - tag: div
          class: main-content-wrap
    article-links-filter-patterns:
        - ^/.*/\d+
        - ^http://.*.zhihu.com/.*/\d+

    # parameters to parse article content
    article-content-container:
        - tag: div
          class: main-wrap content-wrap
    article-content-title:
        tag: h1
        class: headline-title
    article-content:
        - tag: div
          class: question
              
jianshu:
    # general paramters
    name: jianshu
    alias: 简书
    root: http://www.jianshu.com/
    depth: 1
    summary-len: 100

    # parameters to parse home page to get article links 
    home-page-content:
        - tag: div
          id: list-container
    article-links-filter-patterns:
        - ^/p/\w+\d+
        - ^http://.*.jianshu.com/.*/\w+\d+

    # parameters to parse article content
    article-content-container:
        - tag: div
          class: preview
    article-content-title:
        tag: h1
        class: title
    article-content:
        - tag: div
          class: show-content

ftchinese:
    # general paramters
    name: ftchinese
    alias: FT中文
    root: http://www.ftchinese.com/
    depth: 1
    rount: 20
    summary-len: 100

    # parameters to parse home page to get article links 
    home-page-content:
        - tag: div
          id: body-content-col
    article-links-filter-patterns:
        - ^/story/\d+

    # parameters to parse article content
    article-content-container:
        - tag: div
          id: body-content-col
    article-content-title:
        tag: h1
        id: topictitle
    article-content:
        - tag: div
          class: content
          id: bodytext
    article-timestamp:
        - tag: a
          class: storytime

economist:
    # general paramters
    name: economist
    alias: Ecnomist
    root: http://www.economist.com/
    depth: 1
    rount: 20
    summary-len: 100

    headers:
        Host: www.economist.com
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36)

    # parameters to parse home page to get article links 
    home-page-content:
        - tag: div
          id: page
          class: container
    article-links-filter-patterns:
        - ^/news/((?!\?).)*$

    # parameters to parse article content
    article-content-container:
        - tag: div
          id: page
          class: container
    article-content-title:
        tag: h3
        id: headline
    article-content:
        - tag: div
          class: main-content
    article-timestamp:
        - tag: time 
          class: date-created
    article-exclude-tag: aside
 
